[package]
name = "ozz-rust"
version = "0.1.0"
authors = ["FenQiDian <email@fenqi.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
approx = "0.4.0"
bitvec = "0.21.0"
nalgebra = "0.24.1"
